// <auto-generated />
using EstForge.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace EstForge.Data.Migrations
{
    [DbContext(typeof(EstForgeDbContext))]
    partial class EstForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("EstForge.Data.Models.Azienda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AggiornatoIl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatoIl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FontSizeClient")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FontSizeClone")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FontSizeCustomQuote")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FontSizeEditNumber")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FontSizeList")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FontSizeQuote")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FontSizeSettings")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NumerazioneProgressivaAttiva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroProgressivoIniziale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartitaIva")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SedeLegale")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Azienda");
                });

            modelBuilder.Entity("EstForge.Data.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AggiornatoIl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cap")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Citta")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodiceFiscalePIva")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatoIl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeRagioneSociale")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provincia")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Via")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("EstForge.Data.Models.Preventivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AggiornatoIl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Anno")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatoIl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModalitaPagamento")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Oggetto")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ScontoPercentuale")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ScontoValore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotale")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Totale")
                        .HasColumnType("TEXT");

                    b.Property<string>("UbicazioneCap")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("UbicazioneCitta")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UbicazioneProvincia")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("UbicazioneVia")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Preventivi");
                });

            modelBuilder.Entity("EstForge.Data.Models.PreventivoCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AggiornatoIl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Anno")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatoIl")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatiClienteJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModalitaPagamento")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Oggetto")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreventivoOriginaleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RigheJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ScontoPercentuale")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ScontoValore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotale")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoOperazione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Totale")
                        .HasColumnType("TEXT");

                    b.Property<string>("UbicazioneCap")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("UbicazioneCitta")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UbicazioneProvincia")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("UbicazioneVia")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PreventiviCache");
                });

            modelBuilder.Entity("EstForge.Data.Models.RigaPreventivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatoIl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroRiga")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PreventivoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrezzoUnitario")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantita")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Totale")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitaMisura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PreventivoId");

                    b.ToTable("RighePreventivo");
                });

            modelBuilder.Entity("EstForge.Data.Models.Preventivo", b =>
                {
                    b.HasOne("EstForge.Data.Models.Cliente", "Cliente")
                        .WithMany("Preventivi")
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("EstForge.Data.Models.RigaPreventivo", b =>
                {
                    b.HasOne("EstForge.Data.Models.Preventivo", "Preventivo")
                        .WithMany("Righe")
                        .HasForeignKey("PreventivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preventivo");
                });

            modelBuilder.Entity("EstForge.Data.Models.Cliente", b =>
                {
                    b.Navigation("Preventivi");
                });

            modelBuilder.Entity("EstForge.Data.Models.Preventivo", b =>
                {
                    b.Navigation("Righe");
                });
#pragma warning restore 612, 618
        }
    }
}
